package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ElectricalTarification implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.time.Instant timestamp;
	private Integer powerMax;
	private Double costHP;
	private Double costHC;
	private Integer beginHP;
	private Integer endHP;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Heure'.
	 * @return Instant timestamp
	 */
	@Field(smartType = "STyTimestamp", label = "Heure")
	public java.time.Instant getTimestamp() {
		return timestamp;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Heure'.
	 * @param timestamp Instant
	 */
	public void setTimestamp(final java.time.Instant timestamp) {
		this.timestamp = timestamp;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Conso HP'.
	 * @return Integer powerMax
	 */
	@Field(smartType = "STyNumber", label = "Conso HP")
	public Integer getPowerMax() {
		return powerMax;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Conso HP'.
	 * @param powerMax Integer
	 */
	public void setPowerMax(final Integer powerMax) {
		this.powerMax = powerMax;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Cout HP'.
	 * @return Double costHP
	 */
	@Field(smartType = "STyDouble", label = "Cout HP")
	public Double getCostHP() {
		return costHP;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Cout HP'.
	 * @param costHP Double
	 */
	public void setCostHP(final Double costHP) {
		this.costHP = costHP;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Cout HC'.
	 * @return Double costHC
	 */
	@Field(smartType = "STyDouble", label = "Cout HC")
	public Double getCostHC() {
		return costHC;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Cout HC'.
	 * @param costHC Double
	 */
	public void setCostHC(final Double costHC) {
		this.costHC = costHC;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Début HP'.
	 * @return Integer beginHP
	 */
	@Field(smartType = "STyNumber", label = "Début HP")
	public Integer getBeginHP() {
		return beginHP;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Début HP'.
	 * @param beginHP Integer
	 */
	public void setBeginHP(final Integer beginHP) {
		this.beginHP = beginHP;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Fin HP'.
	 * @return Integer endHP
	 */
	@Field(smartType = "STyNumber", label = "Fin HP")
	public Integer getEndHP() {
		return endHP;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Fin HP'.
	 * @param endHP Integer
	 */
	public void setEndHP(final Integer endHP) {
		this.endHP = endHP;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
