package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class GeneralStatus implements DtObject {
	private static final long serialVersionUID = 1L;

	private Boolean initEnCours;
	private Boolean rfPresent;
	private Integer etatWifi;
	private Integer etatTic;
	private Boolean connectInternet;
	private String versionInterface;
	private String versionApp;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'init_en_cours'.
	 * @return Boolean initEnCours
	 */
	@Field(smartType = "STyBoolean", label = "init_en_cours")
	public Boolean getInitEnCours() {
		return initEnCours;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'init_en_cours'.
	 * @param initEnCours Boolean
	 */
	public void setInitEnCours(final Boolean initEnCours) {
		this.initEnCours = initEnCours;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'rf_present'.
	 * @return Boolean rfPresent
	 */
	@Field(smartType = "STyBoolean", label = "rf_present")
	public Boolean getRfPresent() {
		return rfPresent;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'rf_present'.
	 * @param rfPresent Boolean
	 */
	public void setRfPresent(final Boolean rfPresent) {
		this.rfPresent = rfPresent;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'etat_wifi'.
	 * @return Integer etatWifi
	 */
	@Field(smartType = "STyNumber", label = "etat_wifi")
	public Integer getEtatWifi() {
		return etatWifi;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'etat_wifi'.
	 * @param etatWifi Integer
	 */
	public void setEtatWifi(final Integer etatWifi) {
		this.etatWifi = etatWifi;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'etat_tic'.
	 * @return Integer etatTic
	 */
	@Field(smartType = "STyNumber", label = "etat_tic")
	public Integer getEtatTic() {
		return etatTic;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'etat_tic'.
	 * @param etatTic Integer
	 */
	public void setEtatTic(final Integer etatTic) {
		this.etatTic = etatTic;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'connect_internet'.
	 * @return Boolean connectInternet
	 */
	@Field(smartType = "STyBoolean", label = "connect_internet")
	public Boolean getConnectInternet() {
		return connectInternet;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'connect_internet'.
	 * @param connectInternet Boolean
	 */
	public void setConnectInternet(final Boolean connectInternet) {
		this.connectInternet = connectInternet;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'v_interface'.
	 * @return String versionInterface
	 */
	@Field(smartType = "STyLabel", label = "v_interface")
	public String getVersionInterface() {
		return versionInterface;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'v_interface'.
	 * @param versionInterface String
	 */
	public void setVersionInterface(final String versionInterface) {
		this.versionInterface = versionInterface;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'v_app'.
	 * @return String versionApp
	 */
	@Field(smartType = "STyLabel", label = "v_app")
	public String getVersionApp() {
		return versionApp;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'v_app'.
	 * @param versionApp String
	 */
	public void setVersionApp(final String versionApp) {
		this.versionApp = versionApp;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
