package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Thermostat implements Entity {
	private static final long serialVersionUID = 1L;

	private String theCd;
	private String name;
	private Integer power;
	private String observation;
	private Integer signalRf;
	private String signalRfLabel;
	private Boolean blink;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ARooThe",
			fkFieldName = "rooId",
			primaryDtDefinitionName = "DtRoom",
			primaryIsNavigable = true,
			primaryRole = "Room",
			primaryLabel = "Piece",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtThermostat",
			foreignIsNavigable = false,
			foreignRole = "Thermostat",
			foreignLabel = "Radiateur",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<com.mlaroche.smartheater.domain.Room> rooIdAccessor = new StoreVAccessor<>(com.mlaroche.smartheater.domain.Room.class, "Room");

	/** {@inheritDoc} */
	@Override
	public UID<Thermostat> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return String theCd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Code")
	public String getTheCd() {
		return theCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Code'.
	 * @param theCd String <b>Obligatoire</b>
	 */
	public void setTheCd(final String theCd) {
		this.theCd = theCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Nom'.
	 * @return String name
	 */
	@Field(smartType = "STyLabel", label = "Nom")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Nom'.
	 * @param name String
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Puissance'.
	 * @return Integer power
	 */
	@Field(smartType = "STyNumber", label = "Puissance")
	public Integer getPower() {
		return power;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Puissance'.
	 * @param power Integer
	 */
	public void setPower(final Integer power) {
		this.power = power;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Observation'.
	 * @return String observation
	 */
	@Field(smartType = "STyText", label = "Observation")
	public String getObservation() {
		return observation;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Observation'.
	 * @param observation String
	 */
	public void setObservation(final String observation) {
		this.observation = observation;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Signal RF'.
	 * @return Integer signalRf
	 */
	@Field(smartType = "STyNumber", label = "Signal RF")
	public Integer getSignalRf() {
		return signalRf;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Signal RF'.
	 * @param signalRf Integer
	 */
	public void setSignalRf(final Integer signalRf) {
		this.signalRf = signalRf;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Signal RF'.
	 * @return String signalRfLabel
	 */
	@Field(smartType = "STyLabel", label = "Signal RF")
	public String getSignalRfLabel() {
		return signalRfLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Signal RF'.
	 * @param signalRfLabel String
	 */
	public void setSignalRfLabel(final String signalRfLabel) {
		this.signalRfLabel = signalRfLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Clignote'.
	 * @return Boolean blink
	 */
	@Field(smartType = "STyBoolean", label = "Clignote")
	public Boolean getBlink() {
		return blink;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Clignote'.
	 * @param blink Boolean
	 */
	public void setBlink(final Boolean blink) {
		this.blink = blink;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Piece'.
	 * @return Long rooId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Piece", fkDefinition = "DtRoom" )
	public Long getRooId() {
		return (Long) rooIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Piece'.
	 * @param rooId Long <b>Obligatoire</b>
	 */
	public void setRooId(final Long rooId) {
		rooIdAccessor.setId(rooId);
	}

 	/**
	 * Association : Piece.
	 * @return l'accesseur vers la propriété 'Piece'
	 */
	public StoreVAccessor<com.mlaroche.smartheater.domain.Room> room() {
		return rooIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
