package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class WeatherInfo implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.time.Instant timestamp;
	private Double temperature;
	private Double humidity;
	private Integer pressure;
	private Integer clouds;
	private String location;
	private String icon;
	private String description;
	private java.time.Instant sunrise;
	private java.time.Instant sunset;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Heure'.
	 * @return Instant timestamp
	 */
	@Field(smartType = "STyTimestamp", label = "Heure")
	public java.time.Instant getTimestamp() {
		return timestamp;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Heure'.
	 * @param timestamp Instant
	 */
	public void setTimestamp(final java.time.Instant timestamp) {
		this.timestamp = timestamp;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Temperature'.
	 * @return Double temperature
	 */
	@Field(smartType = "STyDouble", label = "Temperature")
	public Double getTemperature() {
		return temperature;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Temperature'.
	 * @param temperature Double
	 */
	public void setTemperature(final Double temperature) {
		this.temperature = temperature;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Humidité'.
	 * @return Double humidity
	 */
	@Field(smartType = "STyDouble", label = "Humidité")
	public Double getHumidity() {
		return humidity;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Humidité'.
	 * @param humidity Double
	 */
	public void setHumidity(final Double humidity) {
		this.humidity = humidity;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Pression'.
	 * @return Integer pressure
	 */
	@Field(smartType = "STyNumber", label = "Pression")
	public Integer getPressure() {
		return pressure;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Pression'.
	 * @param pressure Integer
	 */
	public void setPressure(final Integer pressure) {
		this.pressure = pressure;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété '% de Nuages'.
	 * @return Integer clouds
	 */
	@Field(smartType = "STyNumber", label = "% de Nuages")
	public Integer getClouds() {
		return clouds;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété '% de Nuages'.
	 * @param clouds Integer
	 */
	public void setClouds(final Integer clouds) {
		this.clouds = clouds;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String location
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getLocation() {
		return location;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param location String
	 */
	public void setLocation(final String location) {
		this.location = location;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String icon
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getIcon() {
		return icon;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param icon String
	 */
	public void setIcon(final String icon) {
		this.icon = icon;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String description
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getDescription() {
		return description;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param description String
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Levé de soleil'.
	 * @return Instant sunrise
	 */
	@Field(smartType = "STyTimestamp", label = "Levé de soleil")
	public java.time.Instant getSunrise() {
		return sunrise;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Levé de soleil'.
	 * @param sunrise Instant
	 */
	public void setSunrise(final java.time.Instant sunrise) {
		this.sunrise = sunrise;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Couché de soleil'.
	 * @return Instant sunset
	 */
	@Field(smartType = "STyTimestamp", label = "Couché de soleil")
	public java.time.Instant getSunset() {
		return sunset;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Couché de soleil'.
	 * @param sunset Instant
	 */
	public void setSunset(final java.time.Instant sunset) {
		this.sunset = sunset;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
